# Generated by Django 2.2.11 on 2020-03-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_testing"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="testing",),
    ]
