# Generated by Django 2.2.11 on 2020-03-12 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_customtext_testing"),
        ("users", "0002_auto_20200312_0647"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="neww",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_neww",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="newww",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_newww",
                to="home.HomePage",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="newwww",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_newwww",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
