# Generated by Django 2.2.11 on 2020-03-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_neww"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="neww",),
        migrations.RemoveField(model_name="user", name="newwww",),
    ]
