# Generated by Django 2.2.11 on 2020-03-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200312_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new',
        ),
    ]
